#!/usr/bin/env pwsh
<#
.SYNOPSIS
  M4 Visual Verification — KiwiSDR UI Parity Check via Vision LLM

.DESCRIPTION
  Compares two screenshots (KiwiSDR reference vs. current plugin UI) by sending
  both images to a Vision LLM via OpenRouter API and receiving structured
  feedback on layout/colour/element parity.

  Usage:
    .\scripts\visual-verify.ps1
    .\scripts\visual-verify.ps1 -PluginScreenshot "custom/path.png"
    .\scripts\visual-verify.ps1 -Model "google/gemini-2.5-flash"
    .\scripts\visual-verify.ps1 -Step "M4.2 Header Bar"

  Prerequisites:
    - $env:OPENROUTER_API_KEY set (or hardcoded below for local dev)
    - Reference screenshot at: ui/e2e/reference/kiwisdr-reference.png
    - Plugin screenshot at:    ui/test-results/kiwi-layout-actual.png
      (generated by: npx playwright test e2e/kiwi-layout.spec.ts)

  Output:
    - Console: human-readable summary
    - JSON:    ui/test-results/visual-verify-report.json

.PARAMETER PluginScreenshot
  Path to the current plugin screenshot. Default: ui/test-results/kiwi-layout-actual.png

.PARAMETER ReferenceScreenshot
  Path to the KiwiSDR reference screenshot. Default: ui/e2e/reference/kiwisdr-reference.png

.PARAMETER Model
  OpenRouter model ID for vision analysis.
  Default: anthropic/claude-sonnet-4-6  (best for UI screenshots per 2026 benchmarks)

.PARAMETER Step
  Name of the M4 step being verified (for report metadata). Default: "M4 current"

.PARAMETER ApiKey
  OpenRouter API key. Falls back to $env:OPENROUTER_API_KEY.
#>
param(
  [string]$PluginScreenshot   = "ui/test-results/kiwi-layout-actual.png",
  [string]$ReferenceScreenshot = "ui/e2e/reference/kiwisdr-reference.png",
  [string]$Model               = "anthropic/claude-sonnet-4-6",
  [string]$Step                = "M4 current",
  [string]$ApiKey              = ""
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# --- Resolve paths relative to workspace root ---
$WorkspaceRoot = Split-Path -Parent $PSScriptRoot
$PluginPath    = Join-Path $WorkspaceRoot $PluginScreenshot
$RefPath       = Join-Path $WorkspaceRoot $ReferenceScreenshot
$ReportDir     = Join-Path $WorkspaceRoot "ui/test-results"
$ReportPath    = Join-Path $ReportDir "visual-verify-report.json"

# --- API key ---
if (-not $ApiKey) {
  $ApiKey = $env:OPENROUTER_API_KEY
}
if (-not $ApiKey) {
  Write-Error "OPENROUTER_API_KEY not set. Set the environment variable or pass -ApiKey."
  exit 1
}

# --- Validate inputs ---
if (-not (Test-Path $RefPath)) {
  Write-Error "Reference screenshot not found: $RefPath`nRun: npx playwright test e2e/capture-reference.spec.ts"
  exit 1
}
if (-not (Test-Path $PluginPath)) {
  Write-Error "Plugin screenshot not found: $PluginPath`nRun: npx playwright test e2e/kiwi-layout.spec.ts"
  exit 1
}

Write-Host "=== M4 Visual Verification ===" -ForegroundColor Cyan
Write-Host "Step:      $Step"
Write-Host "Model:     $Model"
Write-Host "Reference: $RefPath"
Write-Host "Plugin:    $PluginPath"
Write-Host ""

# --- Encode images as Base64 ---
function ConvertTo-Base64 {
  param([string]$FilePath)
  $bytes = [System.IO.File]::ReadAllBytes($FilePath)
  return [Convert]::ToBase64String($bytes)
}

Write-Host "Encoding images..." -ForegroundColor Gray
$refBase64    = ConvertTo-Base64 $RefPath
$pluginBase64 = ConvertTo-Base64 $PluginPath

# --- Build prompt ---
$prompt = @"
You are a UI parity expert comparing two screenshots of a software-defined radio (SDR) web interface.

IMAGE 1 (Reference): The original KiwiSDR browser interface — the design target.
IMAGE 2 (Plugin UI): The current Vue.js replica being built for step "$Step".

Analyse both screenshots carefully and respond with ONLY valid JSON (no markdown, no explanation outside the JSON):

{
  "step": "$Step",
  "score": <integer 0-100, overall visual parity percentage>,
  "correct": [
    "<element or region that is correctly implemented>"
  ],
  "missing": [
    "<element present in Reference but absent in Plugin UI>"
  ],
  "deviations": [
    {
      "element": "<name of element>",
      "expected": "<what it looks like in Reference>",
      "actual": "<what it looks like in Plugin UI>"
    }
  ],
  "priority_fixes": [
    "<most impactful fix to improve parity, ordered by importance>"
  ],
  "summary": "<one sentence overall assessment>"
}

Be precise about:
- Exact colours (hex if visible, or descriptive)
- Layout positions (top bar, left side, floating panel, etc.)
- Typography sizes and weights
- Missing UI sections
"@

# --- Build OpenRouter API request body ---
$requestBody = @{
  model    = $Model
  messages = @(
    @{
      role    = "user"
      content = @(
        @{
          type = "text"
          text = $prompt
        },
        @{
          type      = "image_url"
          image_url = @{
            url    = "data:image/png;base64,$refBase64"
            detail = "high"
          }
        },
        @{
          type      = "image_url"
          image_url = @{
            url    = "data:image/png;base64,$pluginBase64"
            detail = "high"
          }
        }
      )
    }
  )
  max_tokens       = 2000
  temperature      = 0.1
} | ConvertTo-Json -Depth 20

# --- Call OpenRouter API ---
Write-Host "Sending to OpenRouter ($Model)..." -ForegroundColor Gray

$headers = @{
  "Authorization" = "Bearer $ApiKey"
  "Content-Type"  = "application/json"
  "HTTP-Referer"  = "https://github.com/artqcid/wogd-vst-netsdrstation"
  "X-Title"       = "NetSDRStation M4 Visual Verify"
}

try {
  $response = Invoke-RestMethod `
    -Uri "https://openrouter.ai/api/v1/chat/completions" `
    -Method POST `
    -Headers $headers `
    -Body $requestBody `
    -TimeoutSec 120
} catch {
  Write-Error "OpenRouter API call failed: $_"
  exit 1
}

# --- Extract and parse JSON response ---
$rawContent = $response.choices[0].message.content
Write-Host ""
Write-Host "--- Raw LLM response ---" -ForegroundColor DarkGray
Write-Host $rawContent
Write-Host ""

# Strip markdown code fences if present
$jsonContent = $rawContent -replace '```json\s*', '' -replace '```\s*', ''
$jsonContent = $jsonContent.Trim()

try {
  $report = $jsonContent | ConvertFrom-Json
} catch {
  Write-Warning "Could not parse JSON response. Saving raw output."
  $report = @{
    step    = $Step
    score   = -1
    raw     = $rawContent
    error   = "JSON parse failed"
  }
}

# --- Add metadata ---
$reportWithMeta = @{
  timestamp   = (Get-Date -Format "yyyy-MM-dd HH:mm:ss")
  step        = $Step
  model       = $Model
  reference   = $RefPath
  plugin      = $PluginPath
  result      = $report
}

# --- Save report ---
New-Item -ItemType Directory -Force -Path $ReportDir | Out-Null
$reportWithMeta | ConvertTo-Json -Depth 20 | Set-Content -Path $ReportPath -Encoding UTF8

# --- Print summary ---
Write-Host "=== RESULT ===" -ForegroundColor Cyan
if ($report.score -ge 0) {
  $scoreColor = if ($report.score -ge 80) { "Green" } elseif ($report.score -ge 50) { "Yellow" } else { "Red" }
  Write-Host "Score:   $($report.score)/100" -ForegroundColor $scoreColor
  Write-Host "Summary: $($report.summary)"
  Write-Host ""

  if ($report.correct -and $report.correct.Count -gt 0) {
    Write-Host "CORRECT ($($report.correct.Count)):" -ForegroundColor Green
    $report.correct | ForEach-Object { Write-Host "  + $_" -ForegroundColor Green }
    Write-Host ""
  }

  if ($report.missing -and $report.missing.Count -gt 0) {
    Write-Host "MISSING ($($report.missing.Count)):" -ForegroundColor Red
    $report.missing | ForEach-Object { Write-Host "  - $_" -ForegroundColor Red }
    Write-Host ""
  }

  if ($report.deviations -and $report.deviations.Count -gt 0) {
    Write-Host "DEVIATIONS ($($report.deviations.Count)):" -ForegroundColor Yellow
    $report.deviations | ForEach-Object {
      Write-Host "  ! $($_.element)" -ForegroundColor Yellow
      Write-Host "      Expected: $($_.expected)" -ForegroundColor DarkYellow
      Write-Host "      Actual:   $($_.actual)" -ForegroundColor DarkYellow
    }
    Write-Host ""
  }

  if ($report.priority_fixes -and $report.priority_fixes.Count -gt 0) {
    Write-Host "PRIORITY FIXES:" -ForegroundColor Magenta
    $i = 1
    $report.priority_fixes | ForEach-Object {
      Write-Host "  $i. $_" -ForegroundColor Magenta
      $i++
    }
    Write-Host ""
  }
}

Write-Host "Report saved: $ReportPath" -ForegroundColor Cyan

# Exit code: non-zero if score < 60
if ($report.score -is [int] -and $report.score -lt 60) {
  Write-Warning "Score below 60 — visual parity not sufficient."
  exit 1
}
exit 0
