#pragma once
// Plugin version and copyright info, used by the Windows resource (plugin.rc).

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by CMake (smtg_target_configure_version_file).
#include "projectversion.h"

#define stringOriginalFilename "netsdrstation.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription "NetSDRStation VST3 (64-bit)"
#else
#define stringFileDescription "NetSDRStation VST3"
#endif
#define stringCompanyName "WOGD"
#define stringCompanyWeb "https://github.com/artqcid"
#define stringCompanyEmail "mailto:info@wogd.example"
#define stringLegalCopyright "(c) 2026 WOGD"
#define stringLegalTrademarks "VST is a trademark of Steinberg Media Technologies GmbH"
